usdoj/foia-api

- config/default/block.block.termsofservice.yml
- config/default/user.role.agency_manager.yml
- docroot/modules/custom/foia_users/src/Plugin/Block/TermsOfService.php
- tests/behat/features/Manager.feature
- tests/behat/features/Saml.feature
> DOJ-148: Adds tests for terms & conds as well as Agency Manager admin theme.

- docroot/sites/default/default.services.yml
- docroot/sites/default/services.yml
Adding settings in order to allow for POST requests from the front stage (for request submission).
> DOJ-172: Add CORS config for POST requests.

- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceApi.php
- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceEmail.php
- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceInterface.php
- docroot/modules/custom/foia_webform/src/Plugin/QueueWorker/FoiaSubmissionQueueWorker.php
- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaSubmissionQueueHandler.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FieldInstallTrait.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FoiaSubmissionQueueHandlerTest.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FoiaSubmissionServiceApiTest.php
https://github.com/18F/beta.foia.gov/issues/215
> DOJ-215: Generate FOIA request upon webform submission

- config/default/mailsystem.settings.yml
- config/default/system.site.yml
- docroot/modules/custom/foia_api/src/Plugin/rest/resource/WebformSubmissionResource.php
- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceEmail.php
- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaEmailWebformHandler.php
https://github.com/18F/beta.foia.gov/issues/118
> DOJ-118: Email Integration

- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceApi.php
- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaEmailWebformHandler.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FoiaSubmissionServiceApiTest.php
- tests/behat/features/Request.feature
https://github.com/usdoj/foia.gov/issues/446
> DOJ-446: Add confirmation ID to email and API transmissions

- docroot/modules/custom/foia_webform/foia_webform.services.yml
- docroot/modules/custom/foia_webform/src/FoiaSubmissionQueueingService.php
- docroot/modules/custom/foia_webform/src/FoiaSubmissionQueueingServiceInterface.php
- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaSubmissionQueueHandler.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FoiaSubmissionQueueHandlerTest.php
https://github.com/usdoj/foia.gov/issues/457
> DOJ-457: Update submission queue handler

- config/default/webform.webform.doj_atf.yml
- config/default/webform.webform.doj_atr.yml
- config/default/webform.webform.doj_bop.yml
- config/default/webform.webform.doj_civil.yml
- config/default/webform.webform.doj_dea.yml
- config/default/webform.webform.doj_oag.yml
- config/default/webform.webform.doj_oasg.yml
- config/default/webform.webform.doj_odag.yml
- config/default/webform_template.webform.yml
- docroot/modules/custom/foia_webform/src/FoiaSubmissionServiceApi.php
- docroot/modules/custom/foia_webform/tests/src/Kernel/FoiaSubmissionServiceApiTest.php
https://github.com/usdoj/foia.gov/issues/485
> DOJ-485: New virus scan status field causing KernelTests to fail

- composer.json
- composer.lock
- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaEmailWebformHandler.php
I closed the branch you commented on earlier. All changes are in this branch now
> Foia api 668 attach request pdf to email

- config/default/views.view.content.yml
New updated from branch "doj-858996-auto-backstage-report"
> DOJ-858996: interoperability_report view has been created on Content.

- docroot/modules/custom/foia_webform/src/Plugin/WebformHandler/FoiaEmailWebformHandler.php
Includes timezone improvements as discussed.
> DOJ-879160_add_timestamps_to_PDFs

- config/default/core.entity_form_display.foia_request.foia_request.default.yml
- config/default/core.entity_view_display.foia_request.foia_request.default.yml
- config/default/field.field.foia_request.foia_request.field_submission_failures.yml
- config/default/field.storage.foia_request.field_submission_failures.yml
- docroot/modules/custom/foia_request/src/Entity/FoiaRequest.php
- docroot/modules/custom/foia_request/src/Entity/FoiaRequestInterface.php
- docroot/modules/custom/foia_webform/src/Plugin/QueueWorker/FoiaSubmissionQueueWorker.php
This adds automatic requeues of failed submissions, up to 5 times.
> DOJ-58: Auto-requeue functionality

- composer.lock
Updating SimpleSAMLPHP library to latest version.
> Updating SimpleSAMLPHP library.

- config/default/block.block.bartik_content.yml
- config/default/block.block.bartik_help.yml
- config/default/block.block.bartik_local_actions.yml
- config/default/block.block.bartik_local_tasks.yml
- config/default/block.block.bartik_page_title.yml
- config/default/block.block.views_block__user_agency_user_agency.yml
- config/default/views.view.annual_foia_report_data_content_1.yml
- config/default/views.view.user_agency.yml
- docroot/modules/custom/foia_annual_data_report/config/install/foia_annual_data_report.settings.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.links.menu.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.module
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.routing.yml
- docroot/modules/custom/foia_annual_data_report/src/Form/MemoryLimitForm.php
- docroot/sites/default/settings.php
* FOIA-178: Increase memory limit on Annual Report form submissions.
* FOIA-178: Add config and settings form for config options to set memory limit value and debug.
> FOIA-178: Increase memory limit on Annual Reports. (#224)

- composer.json
- composer.lock
* FOIA-227: Apply patch to Drupal core to allow long numbers w/decimals.
See https://www.drupal.org/project/drupal/issues/2230909#comment-13267555
* FOIA-227: Update info in composer.lock.
> FOIA-227: Hotfix to allow saving of Annual Reports (#285)

- docroot/modules/custom/foia_upload_xml/src/FailedMigrationHandler/DefaultHandler.php
- docroot/modules/custom/foia_upload_xml/src/FailedMigrationHandler/FailedMigrationHandlerInterface.php
- docroot/modules/custom/foia_upload_xml/src/FailedMigrationHandler/SectionMissing.php
- docroot/modules/custom/foia_upload_xml/src/FoiaUploadXmlMigrateExecutable.php
- docroot/modules/custom/foia_upload_xml/src/FoiaUploadXmlMigrationsProcessor.php
* FOIA-369: Add XML import data missing and default messages.
* FOIA-369: Add documentation.
> FOIA-369: XML import failure messaging. (#354)

- blt/blt.yml
- composer.json
- composer.lock
- config/default/core.extension.yml
- config/default/jsonapi_extras.jsonapi_resource_config.node--agency_component.yml
- config/default/lightning_core.versions.yml
- config/default/views.view.content_cleanup.yml
This adds views bulk operations and the ability to mass-publish.  Check out https://uat-admin.foia.gov/admin/content/cleanup to see an example.
There is a new version of drupal core that the security check is prompting us to upgrade to, but I ran into more dependency issues attempting that, so note the change is blt.yml that disables the security check for now.  We should address the core upgrade as a separate issue.
> Ability to Mass-Publish

- simplesamlphp/config/authsources.php
> Revert "Update authsources.php"

- config/default/field.storage.node.field_overall_ix_lit_costs.yml
- config/default/field.storage.node.field_overall_ix_proc_costs.yml
- config/default/field.storage.node.field_overall_ix_total_costs.yml
- config/default/field.storage.node.field_overall_x_total_fees.yml
Do not merge before release 5.1.0.
> FOIA-0: Config export after changing precision of decimal field.

- simplesamlphp/config/authsources.php
This reverts commit b14ae970fd0b2743aa44dfdc7a6747e4526185e2.
> Revert "Revert "Update authsources.php""

- docroot/modules/custom/foia_export_xml/foia_export_xml.routing.yml
- docroot/modules/custom/foia_export_xml/src/Controller/ExportController.php
> Public API for annual report XML

- config/default/field.field.paragraph.admin_app_via.field_agency_component.yml
- config/default/field.field.paragraph.admin_app_vib.field_agency_component.yml
- config/default/field.field.paragraph.admin_app_vic1.field_agency_component.yml
- config/default/field.field.paragraph.admin_app_vic2.field_agency_component.yml
- config/default/field.field.paragraph.admin_app_vic3.field_agency_component.yml
- config/default/field.field.paragraph.admin_app_vic4.field_agency_component.yml
- config/default/field.field.paragraph.fees_x.field_agency_component.yml
- config/default/field.field.paragraph.foia_pers_costs_ix.field_agency_component.yml
- config/default/field.field.paragraph.foia_req_va.field_agency_component.yml
- config/default/field.field.paragraph.foia_req_vb1.field_agency_component.yml
- config/default/field.field.paragraph.foia_req_vb2.field_agency_component.yml
- config/default/field.field.paragraph.foia_req_vb3.field_agency_component.yml
- config/default/field.field.paragraph.foia_xii_backlogged.field_agency_component.yml
- config/default/field.field.paragraph.foia_xii_received_proc.field_agency_component.yml
- config/default/field.field.paragraph.foia_xiia.field_agency_component.yml
- config/default/field.field.paragraph.foia_xiib.field_agency_component.yml
- config/default/field.field.paragraph.oldest_days.field_agency_component.yml
- config/default/field.field.paragraph.pending_requests_viid.field_agency_component.yml
- config/default/field.field.paragraph.proc_req_viic.field_agency_component.yml
- config/default/field.field.paragraph.processed_requests_vii.field_agency_component.yml
- config/default/field.field.paragraph.quarterly_component_data.field_agency_component.yml
- config/default/field.field.paragraph.req_viiia.field_agency_component.yml
- config/default/field.field.paragraph.req_viiib.field_agency_component.yml
- config/default/field.field.paragraph.statute_agency_details.field_agency_component.yml
- config/default/field.field.paragraph.sub_xia.field_agency_component.yml
- config/default/field.field.paragraph.sub_xib.field_agency_component.yml
> Revert "FOIA-98890: Make all agency fields on reports required."

- .github/workflows/deploy-to-dev.yml
- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- .github/workflows/deploy-to-uat.yml
- composer.json
- composer.lock
> Revert "FOIA-1111: Updated composer and workflows, without simplesaml fix."

- config/default/autosave_form.settings.yml
> Revert "FOIA-0: Export autologout config settings."

- composer.json
- composer.lock
- config/default/core.extension.yml
- config/default/lightning_core.versions.yml
- config/default/xmlsitemap.settings.node.agency_component.yml
- config/default/xmlsitemap.settings.node.cfo_committee.yml
- config/default/xmlsitemap.settings.node.cfo_council.yml
- config/default/xmlsitemap.settings.node.cfo_meeting.yml
- config/default/xmlsitemap.settings.node.cfo_page.yml
- config/default/xmlsitemap.settings.yml
- config/default/xmlsitemap.xmlsitemap.NXhscRe0440PFpI5dSznEVgmauL25KojD7u4e9aZwOM.yml
- docroot/modules/custom/foia_workflow/foia_workflow.module
> Revert "Revert "FOIA-274: XMLSitemap module for components and CFO content.""

- composer.json
removed line: "consolidation/robo": "~1.4.11" from json file
> FOIA-131131: removed consolidation/ robo.

- composer.lock
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.module
- docroot/modules/custom/foia_quarterly_data_report/foia_quarterly_data_report.module
- docroot/modules/custom/foia_users/foia_users.module
this branch included 131131-update composer.json update infos
> FOIA-133121: function Naming Conventions in modules.

- docroot/modules/custom/foia_webform/src/Plugin/QueueWorker/FoiaSubmissionQueueWorker.php
> Revert "FOIA-363: request failed submissions handler."

- docroot/modules/custom/foia_webform/src/Plugin/QueueWorker/FoiaSubmissionQueueWorker.php
> Revert "Revert "FOIA-363: request failed submissions handler.""

- docroot/modules/custom/foia_annual_data_report/js/foia-change-report-agency.js
- docroot/modules/custom/foia_quarterly_data_report/foia_quarterly_data_report.libraries.yml
- docroot/modules/custom/foia_quarterly_data_report/foia_quarterly_data_report.module
- docroot/modules/custom/foia_quarterly_data_report/js/foia-change-report-agency.js
- tests/behat/features/QuarterlyFOIAReportData.feature
* Placeholder test for quarterly reports
* Fixes for placeholder buttons after latest changes
> Fixes for report placeholder buttons after latest changes (#504)

- config/default/core.extension.yml
- config/default/foia_wizard.settings.yml
- docroot/modules/custom/foia_wizard/config/install/foia_wizard.settings.yml
- docroot/modules/custom/foia_wizard/foia_wizard.info.yml
- docroot/modules/custom/foia_wizard/foia_wizard.links.menu.yml
- docroot/modules/custom/foia_wizard/foia_wizard.module
- docroot/modules/custom/foia_wizard/foia_wizard.permissions.yml
- docroot/modules/custom/foia_wizard/foia_wizard.routing.yml
- docroot/modules/custom/foia_wizard/src/Controller/FoiaWizardController.php
- docroot/modules/custom/foia_wizard/src/Form/SettingsForm.php
Adds the `foia_wizard` custom module which creates a new Drupal CMS settings page for the config.
Wizard API endpoint: `/api/foia_wizard`
Path: `/admin/config/system/foia-wizard`
> Added custom FOIA Wizard module

- config/default/foia_wizard.settings.yml
- docroot/modules/custom/foia_wizard/src/Controller/FoiaWizardController.php
- docroot/modules/custom/foia_wizard/src/Form/SettingsForm.php
Updates config content within the `foia_wizard` custom module
Path: `/admin/config/system/foia-wizard`
> Text updates for FOIA Wizard

- .ddev/config.yaml
- .github/workflows/deploy-to-dev.yml
- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- .github/workflows/deploy-to-uat.yml
- .github/workflows/test-pull-requests.yml
- composer.json
- composer.lock
@brockfanning @ameshkin 
Please review my pull request for FOIA PHP update 8.1. This update is for ddev. Developers needs to rebuild.
Thank you
Noor
> FOIA-000: PHP update 8.1 completed.

- config/default/editor.editor.rich_text_wizard.yml
- config/default/filter.format.rich_text_wizard.yml
- config/default/foia_wizard.settings.yml
- docroot/modules/custom/foia_wizard/config/install/foia_wizard.settings.yml
Companion PR: https://github.com/usdoj/foia.gov/pull/1972
> HOTFIX: Content changes to support new CSS

- config/default/webform.webform.dod_sf_form.yml
- config/default/webform_template.webform.yml
Export of an additional webform created on prod.
> FOIA-0000: Adding space force webform to config.

- composer.json
- composer.lock
- config/default/captcha.captcha_point.contact_message_personal_form.yml
- config/default/captcha.captcha_point.node_agency_component_form.yml
- config/default/captcha.captcha_point.node_annual_foia_report_data_form.yml
- config/default/captcha.captcha_point.node_cfo_committee_form.yml
- config/default/captcha.captcha_point.node_cfo_council_form.yml
- config/default/captcha.captcha_point.node_cfo_meeting_form.yml
- config/default/captcha.captcha_point.node_cfo_page_form.yml
- config/default/captcha.captcha_point.node_landing_page_form.yml
- config/default/captcha.captcha_point.node_page_form.yml
- config/default/captcha.captcha_point.node_quarterly_foia_report_data_form.yml
- config/default/captcha.captcha_point.user_login_form.yml
- config/default/captcha.captcha_point.user_pass.yml
- config/default/captcha.captcha_point.user_register_form.yml
- config/default/captcha.settings.yml
- config/default/core.extension.yml
- config/default/entity_clone.cloneable_entities.yml
- config/default/recaptcha.settings.yml
- config/default/webform.webform.doj_jmd.yml
- docroot/modules/custom/foia_api/src/Plugin/rest/resource/WebformSubmissionResource.php
This PR needs to be matched with the WS-50 PR on the front end.
> WS-50 recaptcha request form

- .ddev/config.yaml
- composer.json
- composer.lock
@rgristroph @brockfanning FOIA-0611 PHP Update 8.3
Thank you
Noor
> FOIA-0611: PHP update 8.3 update.

- docroot/modules/custom/foia_api/src/Plugin/rest/resource/WebformSubmissionResource.php
> Revert "WS-503: Added missing use statement."
